<div class="row">
    <ol class="breadcrumb col-md-8">
        <li class="active">Управление пользователями</li>
    </ol>
</div>
<div class="col-md-2" style="margin-bottom: 10px;margin-left: -15px;">
    <select name="role" id="role" class="form-control" onchange="roleChange(this)">
        <option value="">все</option>
        <?php foreach($roles as $rl):?>
            <?php if($rl->getRoleID() != 'guest'):?>
                <option value="<?=$rl->getId();?>" <?php if($role == $rl->getId())echo 'selected'?>><?=$rl->getName()?></option>
            <?php endif;?>
        <?php endforeach;?>
    </select>
</div>

<table class="table table-hover table-bordered table-striped">
    <thead>
    <tr>
        <th style="width: 60px; text-align: center;">№</th>
        <th>ФИО</th>
        <th>Email</th>
        <th>Роли</th>
        <th style="width: 170px; text-align: center;">Действия</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user):?>
        <tr class="<?php if(!$user->getisActive())echo 'notActive';?>">
            <td style="width: 60px; text-align: center;">
                <?=$user->getId()?>
            </td>
            <td>
                <a href="<?=$this->url('admin-user',array('action'=>'view','id'=>$user->getId()))?>">
                    <?=$user->getLastname().' '.$user->getFirstname().' '.$user->getSecondname();?>
                </a>
            </td>
            <td><?=$user->getEmail()?></td>
            <td style="text-align: center; width: 150px;"><?=join(', ',array_map(function($r){ return $r->getName(); },$user->getRoles()))?></td>
            <td style="width: 170px; text-align: center;">
                <a href="<?=$this->url('admin-user',array('action'=>'edit','id'=>$user->getId()))?>" title="Редактировать">
                    <span class="glyphicon glyphicon-edit"></span></a>
                <?php if($user->getIsActive()):?>
                    <a href="javascript:void(0)" onclick="showAction(<?=$user->getId();?>, this)" title="Заблокировать"><span class="glyphicon glyphicon-eye-open"></span></a>
                <?php else:?>
                    <a href="javascript:void(0)" onclick="showAction(<?=$user->getId()?>, this)" title="Разблокировать"><span class="glyphicon glyphicon-eye-close"></span></a>
                <?php endif;?>
                <a href="javascript:void(0)" onclick="if(confirm('Удалить пользователя?'))deleteAction(<?=$user->getId();?>,this);" title="Удалить"><span class="glyphicon glyphicon-remove"></span></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?=$this->paginationControl($users, 'Sliding', 'user-paginator-slide', array('plus'=>array()));?>
<script>
    function roleChange(elem){
        var roleId = $(elem).val();
        var url = (roleId) ? '/admin-users/1/'+roleId : '/admin-users';
        window.location = url;
    }
</script>