<div class="row">
    <ol class="breadcrumb col-md-8">
        <li class="active">Управление данными</li>
    </ol>
    <div class="col-md-4">
        <div class="btn-group btn-group-justified">
            <a href="<?=$this->url('column-data-edit',array('action'=>'edit','id'=>0, 'type'=>$type))?>" class="btn btn-default"> <span class="glyphicon glyphicon-plus"></span> Добавить</a>
        </div>
    </div>
</div>

<table class="table table-hover table-bordered table-striped">
    <thead>
    <tr>
        <th style="width: 60px; text-align: center;">№</th>
        <th>Название</th>
        <th style="width: 170px; text-align: center;">Действия</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->column as $column):?>
        <tr class="<?php if(!$column->getisActive())echo 'notActive';?>">
            <td class="text-center">
                <?=$column->getId()?>
            </td>
            <td>
                <a href="<?=$this->url('column-data-edit',array('action'=>'edit','id'=>$column->getId(), 'type'=>$column->getType()));?>">
                    <?=$column->getName();?>
                </a>
            </td>
            <td class="text-center">
                <a href="<?=$this->url('column-data-edit',array('action'=>'edit','id'=>$column->getId(), 'type'=>$column->getType()));?>" title="Редактировать">
                    <span class="glyphicon glyphicon-edit"></span></a>
                <?php if($column->getIsActive()):?>
                    <a href="javascript:void(0)" onclick="showAction('<?=$this->url('column-data-edit', array('type'=>$column->getType(),'id'=>$column->getId(),'action'=>'show'));?>', this)" title="Скрыть"><span class="glyphicon glyphicon-eye-open"></span></a>
                <?php else:?>
                    <a href="javascript:void(0)" onclick="showAction('<?=$this->url('column-data-edit', array('type'=>$column->getType(),'id'=>$column->getId(),'action'=>'show'));?>', this)" title="Показать"><span class="glyphicon glyphicon-eye-close"></span></a>
                <?php endif;?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?=$this->paginationControl($this->column, 'Sliding', 'columndata-paginator-slide', array('plus'=>array('type'=>$this->type)));?>
<script>
    function showAction(url, elem){
        var button = $(elem);
        var trigger = button.closest('tr').hasClass('notActive');
        $.post(url,{'act':trigger},function(res){
            if(res.status === 'ok'){
                if(trigger){
                    button.closest('tr').removeClass('notActive');
                    button.find('span').removeClass('glyphicon-eye-close').addClass('glyphicon-eye-open');

                }else{
                    button.closest('tr').addClass('notActive');
                    button.find('span').removeClass('glyphicon-eye-open').addClass('glyphicon-eye-close');
                }

            }
        },'JSON');
    }
</script>