<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/script.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>">АС</a>
            </div>

            <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
<!--                        <li class="dropdown">-->
<!--                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Настройки <b class="caret"></b></a>-->
<!--                            <ul class="dropdown-menu">-->
<!--                                <li><a href="#">Пользователи</a></li>-->
<!--                                <li><a href="#">Создание Sitemap</a></li>-->
<!--                            </ul>-->
<!--                        </li>-->
                        <li>
                            <a href="<?php echo $this->url('zfcuser/logout');?>" title="Выход из системы"><span class="glyphicon glyphicon-log-out"></span> Выход</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav">
                        <li <?php if($this->menu_select_sub=='edit-me'):?> class="active"<?php endif; ?>>
                            <a href="<?=$this->url('user', array('action'=>'edit'));?>">Мои данные</a>
                        </li>
                        <?php if(in_array('admin',$this->layout()->roles)):?>
                        <li class="dropdown <?php if(in_array($this->menu_select_sub, array('admin-users','admin-position','admin-rate','admin-rank','admin-degree', 'admin-unit'))) echo 'active';?>">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Администрирование <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li <?php if($this->menu_select_sub=='admin-users'):?> class="active"<?php endif; ?>>
                                    <a href="<?=$this->url('admin-user');?>">Пользователи</a>
                                </li>
                                <li <?php if($this->menu_select_sub=='admin-position'):?> class="active"<?php endif; ?>>
                                    <a href="<?php echo $this->url('column-data', array('type'=> 'position'));?>">Должность</a>
                                </li>
                                <li <?php if($this->menu_select_sub=='admin-rate'):?> class="active"<?php endif; ?>>
                                    <a href="<?php echo $this->url('column-data', array('type'=> 'rate'));?>">Cтавка</a>
                                </li>
                                <li <?php if($this->menu_select_sub=='admin-rank'):?> class="active"<?php endif; ?>>
                                    <a href="<?php echo $this->url('column-data', array('type'=> 'rank'));?>">Ученое звание</a>
                                </li>
                                <li <?php if($this->menu_select_sub=='admin-degree'):?> class="active"<?php endif; ?>>
                                    <a href="<?php echo $this->url('column-data', array('type'=> 'degree'));?>">Научная степень</a>
                                </li>
                                <li <?php if($this->menu_select_sub=='admin-unit'):?> class="active"<?php endif; ?>>
                                    <a href="<?php echo $this->url('admin-unit');?>">Институты и кафедры</a>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>
                    </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container-fluid" style="max-width: 95%; margin: auto;">
        <div style="min-height: 450px;">
            <?php echo $this->content; ?>
        </div>
        <hr>
        <footer>
            <p>&copy; <?php echo date('Y') ?> by ONAT <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
    </div> <!-- /container -->
    <div id="ok-alert" class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        Данные успешно сохранены.</div>
    <div id="warning-alert" class="alert alert-warning" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        Данные успешно удалены.</div>
    <?php echo $this->inlineScript() ?>
    </body>
</html>
