<div class="page-header">
    <h3 class="text-center">Редактирования профилия</h3>
</div>


<?php echo $this->form()->openTag($form); ?>
<div class="col-md-offset-2">
    <div class="form-group clearfix">
        <?=$this->formLabel($form->get('lastname'));?>
        <div class="col-md-6">
            <?=$this->formElement($form->get('lastname'));?>
        </div>

    </div>
    <div class="form-group clearfix">
        <?=$this->formLabel($form->get('firstname'));?>
        <div class="col-md-6">
            <?=$this->formElement($form->get('firstname'))?>
        </div>
    </div>
    <div class="form-group clearfix">
        <?=$this->formLabel($form->get('secondname'));?>
        <div class="col-md-6">
            <?=$this->formElement($form->get('secondname'))?>
        </div>
    </div>
    <div class="form-group col-md-offset-4">
        <button class="btn btn-default" type="submit">Сохранить</button>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>
