<div class="page-header">
    <h3 class="text-center">Редактирования профилия</h3>
</div>


<?php echo $this->form()->openTag($form); ?>
<div class="col-md-offset-2">
    <div class="form-group clearfix">
        <?=$this->formLabel($form->get('lastname'));?>
        <div class="col-md-6">
            <?=$this->formElement($form->get('lastname'));?>
        </div>

    </div>
    <div class="form-group clearfix">
        <?=$this->formLabel($form->get('firstname'));?>
        <div class="col-md-6">
            <?=$this->formElement($form->get('firstname'))?>
        </div>
    </div>
    <div class="form-group clearfix">
        <?=$this->formLabel($form->get('secondname'));?>
        <div class="col-md-6">
            <?=$this->formElement($form->get('secondname'))?>
        </div>
    </div>
    <div class="form-group clearfix">
        <?=$this->formLabel($form->get('institute'));?>
        <div class="col-md-6">
            <?=$this->formElement($form->get('institute'))?>
        </div>
    </div>
    <div class="form-group clearfix">
        <?=$this->formLabel($form->get('chair'));?>
        <div class="col-md-6">
            <?=$this->formElement($form->get('chair'))?>
        </div>
    </div>
    <div class="form-group col-md-offset-4">
        <button class="btn btn-default" type="submit">Сохранить</button>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>
<script type="text/javascript">
    (function($){
        $(function(){
            $('#institute').off('change').on('change', function(event){
                var institute = $(event.target),
                    val = institute.val(),
                    chair = $('#chair');

                chair.html('');
                chair.append($('<option value="">').text('Не выбрано'));

                if(!val)return false;

                $.post('<?php echo $this->url('unit', array('action'=>'getchildrenunits'))?>',{id:val},function(res){

                    var result = res.result;

                    $.each(result, function(key, value){
                        var option = $('<option>').attr('value',key).text(value);
                        chair.append(option);
                    });

                },'JSON');
            });
        });
    })(jQuery);
</script>