<h3 class="text-center">
    Редактирования профилия
</h3>
<?php echo $this->form()->openTag($form);?>
    <div class="form-group">
        <?php echo $this->form()->openTag($form);?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('lastname'));?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('firstname'));?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('secondname'));?>
    </div>
    <button type="submit" class="btn btn-default">Сохранить</button>
<?php echo $this->form()->closeTag();?>